[build]
  command = "hugo"
  publish = "public"

[[redirects]]
  from = "/auth"
  to = "https://github.com/login/oauth/authorize"
  status = 302
  force = true
  query = {client_id = "${GITHUB_CLIENT_ID}", redirect_uri = "${SITE_URL}/admin/", scope = "repo"}

[[redirects]]
  from = "/callback"
  to = "https://github.com/login/oauth/access_token"
  status = 302
  force = true
  query = {client_id = "${GITHUB_CLIENT_ID}", client_secret = "${GITHUB_CLIENT_SECRET}", code = "${code}", redirect_uri = "${SITE_URL}/admin/"}

[context.production.environment]
  HUGO_VERSION = "0.111.3"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.split1]
  command = "hugo --gc --minify --enableGitInfo"
  
[context.split1.environment]
  HUGO_VERSION = "0.111.3"
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
