backend:
  name: github
  repo: simbav911/dart-naujas-btcz.rock
  branch: main
  client_id: Ov23likVSo2M8nWaTKxA
  base_url: https://api.github.com
  auth_endpoint: login/oauth/authorize
  site_domain: simbav911.github.io

publish_mode: editorial_workflow

media_folder: static/images
public_folder: /images

collections:
  - name: news
    label: "News Posts"
    folder: content/news
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: title, widget: string}
      - {label: "Publish Date", name: date, widget: datetime}
      - {label: "Featured Image", name: image, widget: image, required: false}
      - {label: "Body", name: body, widget: markdown}

  - name: content
    label: "Pages"
    folder: content
    create: true
    fields:
      - {label: "Title", name: title, widget: string}
      - {label: "Body", name: body, widget: markdown}