backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "news"
    label: "News"
    folder: "content/en/news"
    create: true
    slug: "{{year}}-{{month}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subject", name: "subject", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Summary", name: "summary", widget: "text", required: false}

  - name: "exchanges"
    label: "Exchange Listings"
    folder: "content/en/buy/exchanges"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Exchange Name", name: "title", widget: "string", hint: "Enter the name of the exchange"}
      - {label: "Description", name: "description", widget: "text", hint: "Brief description of the exchange (2-3 sentences)"}
      - {label: "Date Added", name: "date", widget: "datetime"}
      - {
          label: "Exchange Logo", 
          name: "image", 
          widget: "image", 
          hint: "Upload a PNG logo with transparent background (recommended size: 200x200px)",
          media_library: {
            config: {
              multiple: false
            }
          }
        }
      - {label: "Exchange Type", name: "type", widget: "hidden", default: "exchange"}
      - {label: "Categories", name: "categories", widget: "hidden", default: ["Exchange"]}
      - {
          label: "Exchange Features", 
          name: "features", 
          widget: "list", 
          hint: "Add key features of the exchange",
          min: 2,
          max: 6
        }
      - {
          label: "Trading Pairs", 
          name: "trading_pairs", 
          widget: "list",
          hint: "Add available trading pairs (e.g., 'BTCZ/BTC')",
          min: 1
        }
      - {
          label: "Exchange Website URL", 
          name: "website", 
          widget: "string",
          hint: "Full URL including https://"
        }
      - {
          label: "KYC Required?", 
          name: "kyc_required", 
          widget: "boolean", 
          default: false,
          hint: "Select Yes if KYC verification is required"
        }
      - {label: "Draft", name: "draft", widget: "boolean", default: false}

  - name: "wallets"
    label: "Wallet Listings"
    folder: "content/en/wallets"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Wallet Name", name: "title", widget: "string", hint: "Enter the name of the wallet"}
      - {label: "Description", name: "description", widget: "text", hint: "Brief description of the wallet features"}
      - {label: "Date Added", name: "date", widget: "datetime"}
      - {
          label: "Wallet Logo", 
          name: "image", 
          widget: "image", 
          hint: "Upload a PNG logo with transparent background (recommended size: 200x200px)",
          media_library: {
            config: {
              multiple: false
            }
          }
        }
      - {
          label: "Gallery Images", 
          name: "gallery", 
          widget: "list",
          field: {label: Image, name: image, widget: image},
          hint: "Add screenshots or additional images (recommended size: 1200x675px)",
          required: false
        }
      - {label: "Type", name: "type", widget: "hidden", default: "wallet"}
      - {
          label: "Features", 
          name: "features", 
          widget: "list", 
          hint: "Add key features of the wallet",
          min: 2,
          max: 6
        }
      - {
          label: "Platforms", 
          name: "platforms", 
          widget: "list",
          hint: "Add download information for each supported platform",
          fields:
            - {label: "Platform Name", name: "name", widget: "select", options: ["Windows", "macOS", "Linux", "Android", "iOS", "Web"]}
            - {label: "Download URL", name: "download_url", widget: "string"}
            - {label: "Version", name: "version", widget: "string"}
        }
      - {
          label: "System Requirements", 
          name: "requirements", 
          widget: "list",
          hint: "Add system requirements for the wallet",
          required: false
        }
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {
          label: "Detailed Description", 
          name: "body", 
          widget: "markdown", 
          hint: "Add detailed information about the wallet",
          required: false
        }

  - name: "pages"
    label: "Page Settings"
    files:
      - name: "wallets-index"
        label: "Wallets Page Content"
        file: "content/en/wallets/_index.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Type", name: "type", widget: "hidden", default: "section"}
          - {label: "Layout", name: "layout", widget: "hidden", default: "wallets"}
          - {
              label: "Safety Tips", 
              name: "safety_tips", 
              widget: "list",
              hint: "Add wallet safety tips for users",
              min: 2,
              max: 5
            }
