backend:
  name: git-gateway
  branch: main

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "roadmap"
    label: "Roadmap"
    folder: "content/roadmap"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Section", name: "section", widget: "hidden", default: "roadmap"}
      - {label: "Type", name: "type", widget: "hidden", default: "roadmap"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "single"}
      - {label: "Year", name: "year", widget: "number"}
      - {label: "Status", name: "status", widget: "select", options: ["completed", "in-progress", "upcoming"]}
      - {label: "Progress", name: "progress", widget: "number", min: 0, max: 100, default: 0}
      - {label: "Tags", name: "tags", widget: "select", multiple: true, options: ["Mining", "Exchange", "Community", "Wallet", "Payment", "Media", "Update", "Video", "Launch"]}
      - {label: "Icon", name: "icon", widget: "image", media_folder: "/static/images/icons"}
      - {label: "Priority", name: "priority", widget: "select", options: ["high", "medium", "low"]}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "icons"
    label: "Icons"
    folder: "static/images/icons"
    create: true
    extension: "svg"
    format: "raw"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "SVG Content", name: "body", widget: "code", default_language: "svg"}
