backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "news"
    label: "News"
    folder: "content/en/news"
    create: true
    slug: "{{year}}-{{month}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subject", name: "subject", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Summary", name: "summary", widget: "text", required: false}

  - name: "exchanges"
    label: "Exchange Listings"
    folder: "content/en/buy/exchanges"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Exchange Name", name: "title", widget: "string", hint: "Enter the name of the exchange"}
      - {label: "Description", name: "description", widget: "text", hint: "Brief description of the exchange (2-3 sentences)"}
      - {label: "Date Added", name: "date", widget: "datetime"}
      - {
          label: "Exchange Logo", 
          name: "image", 
          widget: "image", 
          hint: "Upload a PNG logo with transparent background (recommended size: 200x200px)",
          media_library: {
            config: {
              multiple: false
            }
          }
        }
      - {label: "Exchange Type", name: "type", widget: "hidden", default: "exchange"}
      - {label: "Categories", name: "categories", widget: "hidden", default: ["Exchange"]}
      - {
          label: "Exchange Features", 
          name: "features", 
          widget: "list", 
          hint: "Add key features of the exchange (e.g., 'Low Trading Fees', '24/7 Support')",
          min: 2,
          max: 6
        }
      - {
          label: "Trading Pairs", 
          name: "trading_pairs", 
          widget: "list",
          hint: "Add available trading pairs (e.g., 'BTCZ/BTC', 'BTCZ/USDT')",
          min: 1
        }
      - {
          label: "Exchange Website URL", 
          name: "website", 
          widget: "string",
          hint: "Full URL including https:// (e.g., https://exchange.com)"
        }
      - {
          label: "KYC Required?", 
          name: "kyc_required", 
          widget: "boolean", 
          default: false,
          hint: "Select Yes if the exchange requires KYC verification"
        }
      - {
          label: "Draft", 
          name: "draft", 
          widget: "boolean", 
          default: false,
          hint: "Set to Yes to hide this exchange from the website"
        }
      - {
          label: "Additional Information", 
          name: "body", 
          widget: "markdown", 
          required: false,
          hint: "Optional: Add any additional details about the exchange"
        }

  - name: "buy-page"
    label: "Buy Page Settings"
    files:
      - name: "buy-index"
        label: "Buy Page Content"
        file: "content/en/buy/_index.md"
        fields:
          - {label: "Title", name: "title", widget: "string", hint: "Main title of the buy page"}
          - {label: "Description", name: "description", widget: "text", hint: "Brief description shown under the title"}
          - {label: "Type", name: "type", widget: "hidden", default: "section"}
          - {label: "Layout", name: "layout", widget: "hidden", default: "buy"}
          - {
              label: "Safety Tips", 
              name: "safety_tips", 
              widget: "list",
              hint: "Add safety tips for users (displayed at bottom of page)",
              min: 2,
              max: 5
            }
