backend:
  name: github
  repo: simbav911/dart-naujas-btcz.rock
  branch: main
  base_url: https://api.github.com
  auth_endpoint: oauth/authorize
  client_id: Ov23likVSo2M8nWaTKxA

media_folder: static/images
public_folder: /images

collections:
  - name: "news"
    label: "News"
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
