baseURL = "https://simbav911.github.io/dart-naujas-btcz.rock/"

[params]
  env = "production"

[build]
  writeStats = true

[server]
  [[server.headers]]
    for = "/images/*"
    [server.headers.values]
      Cache-Control = "public, max-age=31536000"

[security]
  [security.http]
    useHTTPS = true

[minify]
  minifyOutput = true
