baseURL = "https://getbtcz.com"

[params]
  brevo_api_key = "xkeysib-YOUR-API-KEY-HERE"
  brevo_list_id = "YOUR-LIST-ID-HERE"

[permalinks]
  why-bitcoinz = "/:sections/:filename/"

[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 301
  force = true
