baseURL = "https://getbtcz.com"

[params]
  brevo_api_key = "${BREVO_API_KEY}"
  brevo_list_id = "${BREVO_LIST_ID}"

[permalinks]
  why-bitcoinz = "/:sections/:filename/"

[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 301
  force = true
