backend:
  name: github
  repo: simbav911/dart-naujas-btcz.rock
  branch: main

local_backend: true
site_url: https://simbav911.github.io/dart-naujas-btcz.rock
display_url: https://simbav911.github.io/dart-naujas-btcz.rock
logo_url: /dart-naujas-btcz.rock/images/btcz-logo.png

media_folder: static/images
public_folder: /images

collections:
  - name: "news"
    label: "News"
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string", default: "BitcoinZ Team"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Type", name: "type", widget: "hidden", default: "news"}
      - {label: "Categories", name: "categories", widget: "select", multiple: true, options: ["Community", "Development", "Exchange", "Mining", "Partnership", "Update"]}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "single"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "wallet"
    label: "Wallet"
    folder: "content/wallet"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Download URL", name: "download_url", widget: "string"}
      - {label: "Platform", name: "platform", widget: "select", options: ["Windows", "macOS", "Linux", "Android", "iOS"]}
      - {label: "Body", name: "body", widget: "markdown"}
