backend:
  name: github
  repo: simbav911/dart-naujas-btcz.rock
  branch: main
  client_id: Ov23likVSo2M8nWaTKxA
  auth_type: implicit
  base_url: https://api.github.com

# Media handling
media_folder: static/images
public_folder: /images

# Collections
collections:
  - name: news
    label: News
    folder: content/news
    create: true
    fields:
      - {label: Title, name: title, widget: string}
      - {label: "Publish Date", name: date, widget: datetime}
      - {label: "Featured Image", name: image, widget: image, required: false}
      - {label: Body, name: body, widget: markdown}

# Development settings
local_backend: true
