name: Hugo Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Node.js dependencies
        run: npm install

      - name: Generate Brevo Config
        env:
          BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}
          BREVO_LIST_ID: ${{ secrets.BREVO_LIST_ID }}
        run: node scripts/generate-brevo-config.js

      - name: Verify Brevo Config
        run: |
          if [ ! -f "static/js/brevo-config.js" ]; then
            echo "Error: brevo-config.js was not generated"
            exit 1
          fi
          echo "Verifying brevo-config.js structure..."
          grep -q "window.BREVO_CONFIG" static/js/brevo-config.js || (echo "Error: Missing BREVO_CONFIG object" && exit 1)
          echo "brevo-config.js verification completed"

      - name: Build
        env:
          HUGO_ENV: production
        run: hugo --minify

      - name: Verify Built Files
        run: |
          echo "Checking built files..."
          if [ ! -f "public/js/brevo-config.js" ]; then
            echo "Error: brevo-config.js not found in build output"
            echo "Contents of public/js/:"
            ls -la public/js/ || echo "js directory not found"
            exit 1
          fi
          echo "Built files verification completed"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: getbtcz.com
