name: Hugo Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      HUGO_ENV: production
      HUGO_VERSION: 0.140.0
      
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{ env.HUGO_VERSION }}
          extended: true

      - name: Verify Hugo Installation
        run: hugo version

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Node.js dependencies
        run: npm install

      - name: Generate Brevo Config
        env:
          BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}
          BREVO_LIST_ID: ${{ secrets.BREVO_LIST_ID }}
        run: |
          mkdir -p static/js
          if [ ! -z "$BREVO_API_KEY" ] && [ ! -z "$BREVO_LIST_ID" ]; then
            node scripts/generate-brevo-config.js
          else
            echo "window.BREVO_CONFIG = { disabled: true };" > static/js/brevo-config.js
          fi

      - name: List Project Structure
        run: |
          echo "Project structure:"
          ls -la
          echo "Theme directory:"
          ls -la themes/PaperMod
          echo "Layouts directory:"
          ls -la layouts/
          echo "Partials directory:"
          ls -la layouts/partials/

      - name: Build Hugo Site
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENABLEGITINFO: true
        run: |
          hugo --logLevel debug --verbose --minify --gc

      - name: Check Build Output
        if: always()
        run: |
          echo "Checking build output..."
          if [ -d "public" ]; then
            echo "Content of public directory:"
            ls -la public/
          else
            echo "public directory not found!"
            echo "Current directory contents:"
            ls -la
          fi

      - name: Deploy
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          cname: getbtcz.com
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: ${{ github.event.head_commit.message }}
