name: Hugo Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.140.0'
          extended: true

      - name: Verify Hugo Installation
        run: hugo version

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Node.js dependencies
        run: npm install

      - name: Generate Brevo Config
        if: ${{ env.BREVO_API_KEY != '' && env.BREVO_LIST_ID != '' }}
        env:
          BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}
          BREVO_LIST_ID: ${{ secrets.BREVO_LIST_ID }}
        run: node scripts/generate-brevo-config.js

      - name: Create Empty Brevo Config
        if: ${{ env.BREVO_API_KEY == '' || env.BREVO_LIST_ID == '' }}
        run: |
          mkdir -p static/js
          echo "window.BREVO_CONFIG = { disabled: true };" > static/js/brevo-config.js

      - name: List Project Structure
        run: |
          echo "Project structure:"
          ls -la
          echo "Theme directory:"
          ls -la themes/PaperMod

      - name: Build with Debug
        env:
          HUGO_ENV: production
          HUGO_LOGFILE: hugo.log
        run: |
          hugo --logFile hugo.log --verbose --debug --minify || (cat hugo.log && exit 1)

      - name: Check Build Output
        if: always()
        run: |
          echo "Checking build output..."
          if [ -d "public" ]; then
            echo "Content of public directory:"
            ls -la public/
          else
            echo "public directory not found!"
          fi

      - name: Deploy
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: getbtcz.com
